---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
---


```{r}
load("Data/input.Rdata")
```


```{r}
# Fit model on contiuous variables
train_num <- train %>% select(var_num,loss)

fitlm <- lm(loss ~ ., data = train_num)

pred <- predict(fitlm)
```

Support vector machines:

```{r}
library(caret)

#input <- select(train_rs,-var_cat)
input <- select(train_rs,71:80,loss)

svmFit <- train(loss ~ .,
                data = input,
                method = "svmRadial",
                tuneLength = 5,
                trControl = trainControl(method = "repeatedcv",
                                         repeats = 5))

plot(svmFit, scales = list(x = list(log = 2)))

pred <- predict(svmFit, input)

plot(pred,input$loss)
```

CART:

```{r}
input <- select(train_rs,-var_cat)
#input <- select(train_rs,71:80,loss)

cartFit <- train(loss ~ ., 
                   data=input, 
                   method = "rpart", 
                   tuneLength=5,
                   trControl = trainControl(method = "repeatedcv",
                                            repeats = 5))

plot(cartFit, scales = list(x = list(log = 2)))

pred <- predict(cartFit, input)

plot(pred,input$loss)
```

C5.0:

```{r}
library(plyr); library(dplyr)

input <- select(train_rs,1:10,loss)

c50Fit <- train(loss ~ ., 
                   data=input, 
                   method = "C5.0", 
                   tuneLength=5,
                   trControl = trainControl(method = "repeatedcv",
                                            repeats = 5))

plot(c50Fit, scales = list(x = list(log = 2)))

pred <- predict(c50Fit, input)

plot(pred,input$loss)
```

Boosted trees:

```{r}
input <- select(train_rs,1:10,loss)

gbmFit <- train(loss ~ ., 
                   data=input, 
                   method = "gbm", 
                   tuneLength=5,
                   verbose=FALSE,
                   trControl = trainControl(method = "repeatedcv",
                                            repeats = 5))

plot(gbmFit, scales = list(x = list(log = 2)))

pred <- predict(gbmFit, input)

plot(pred,input$loss)
```


Random forest:

```{r}
input <- select(train_rs,71:80,loss)

rfFit <- train(loss ~ ., 
                   data=input, 
                   method = "rf", 
                   tuneLength=5,
                   verbose=FALSE,
                   trControl = trainControl(method = "repeatedcv",
                                            repeats = 5))

plot(rfFit, scales = list(x = list(log = 2)))

pred <- predict(rfFit, input)

plot(pred,input$loss)
```

xgboost:


```{r}
library(xgboost)

input_x <- select(train_num,-loss)
input_y <- train_num$loss

dtrain <- xgb.DMatrix(as.matrix(input_x), label=as.matrix(input_y))

feval <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  err <- sum(abs(exp(labels) - exp(preds)))/length(labels)
  return(list(metric = "error", value = err))
}

obj_func <- function(preds, dtrain) {
  labels <- getinfo(dtrain, "label")
  grad <- tanh(preds-labels)
  hess <- 1-grad*grad
  return(list(grad = grad, hess = hess))
}

# Initialize
p <- c(6,12)
mdcv_list <- list()
n_rounds_best <- NULL
i_best <- NULL
min_loss_best <- 1e12

for (i in length(p)){
  
  param <- list(
    objective = obj_func,
    eval_metric = feval,
    max_depth = p[i],
    eta = 0.03,
    base_score = 7.76
  )
  
  cv.nround = 1000
  cv.nfold = 5
  
  mdcv <- xgb.cv(data = dtrain, 
                 params = param, 
                 nthread=4, 
                 nfold=cv.nfold, 
                 nrounds=cv.nround,
                 verbose = T)
  
  mdcv_list[[i]] <- mdcv
  
  min_loss = min(mdcv$evaluation_log[, test_error_mean])
  
  if (min_loss<min_loss_best){
    i_best <- i
    nrounds_best <- which.min(mdcv$evaluation_log[, test_error_mean])
  }
}

param <- list(
  objective = obj_func,
  eval_metric = feval,
  max_depth = p[i_best],
  eta = 0.03,
  base_score = 7.76
)

md_best <- xgb.train(data=dtrain, params=param, nrounds=nrounds_best, nthread=4)

pred <- exp(predict(md_best, as.matrix(test_num)))
```

```{r}
out <- id_test %>% mutate(loss=pred)
write_csv(out,"Submissions/submission1.csv")
```

